CREATE DATABASE TESTE;

USE TESTE; 

CREATE TABLE PRODUTO (
   COD_PRODUTO INTEGER       PRIMARY KEY AUTO_INCREMENT,
   NOME_PRODUTO  VARCHAR (100) NOT NULL,
   VALOR_UNITARIO DECIMAL(12.2)  NOT NULL
);

INSERT INTO PRODUTO (NOME_PRODUTO,VALOR_UNITARIO) VALUES ('KIT FERRAMENTAS',90.00);
INSERT INTO PRODUTO (NOME_PRODUTO,VALOR_UNITARIO) VALUES ('SMARTPHONE ', 850.00 );
INSERT INTO PRODUTO (NOME_PRODUTO,VALOR_UNITARIO) VALUES ('CAMA BOX CASAL',2500.00);
INSERT INTO PRODUTO (NOME_PRODUTO,VALOR_UNITARIO) VALUES ('REFRIGERADOR',2800);
INSERT INTO PRODUTO (NOME_PRODUTO,VALOR_UNITARIO) VALUES ('SOFA 3 LUGARES',1700);

SELECT * FROM PRODUTO;

/* EXEMPLO PROCEDURE IN */
DELIMITER // 
CREATE PROCEDURE exibir_produtos( IN QUANTIDADE INT)
BEGIN 
   SELECT 
      * 
    FROM PRODUTO AS P 
    LIMIT QUANTIDADE;
 END//
 
 // -- CHAMADA DA PROCEDURE
 CALL exibir_produtos(3);

/* EXEMPLO PROCEDURE OUT */
DELIMITER //
CREATE PROCEDURE contar_produtos(OUT QUANTIDADE INT)
BEGIN 
   SELECT 
      COUNT(*) INTO QUANTIDADE
	FROM PRODUTO AS P;
 END //    
 
 // -- CHAMADA DA PROCEDURE
CALL contar_produtos(@quantidade);
select @quantidade;

/* exemplo PROCEDURE INOUT */
DELIMITER //
CREATE PROCEDURE POTENCIA2(INOUT VALOR INT)
BEGIN 
   SET VALOR = VALOR * VALOR;
END//

// -- CHAMADA DA PROCEDURE
SET @NUMERO = 2;
CALL POTENCIA2(@NUMERO);
select @NUMERO;


/* EXEMPLO TRIGGER */
CREATE TABLE HISTORICO_PRODUTO (
   ID           INTEGER   PRIMARY KEY AUTO_INCREMENT,
   COD_PRODUTO  INTEGER   NOT NULL,
   DATA         DATETIME  NOT NULL,
   VALOR_ANTERIOR DECIMAL(12.2)  NOT NULL,
   VALOR_NOVO   DECIMAL(12.2)  NOT NULL
); 

SELECT * FROM HISTORICO_PRODUTO;

/* TRIGGER */
DELIMITER // 
CREATE TRIGGER HISTORICO_DE_PRODUTO
AFTER UPDATE ON PRODUTO 
  FOR EACH ROW
  BEGIN 
     IF NEW.VALOR_UNITARIO <> OLD.VALOR_UNITARIO THEN 
        INSERT INTO HISTORICO_PRODUTO (COD_PRODUTO,DATA,VALOR_ANTERIOR, VALOR_NOVO)
              VALUES (NEW.COD_PRODUTO,CURDATE(),OLD.VALOR_UNITARIO,NEW.VALOR_UNITARIO);
	 END IF; 
END //     

/* TESTE TRIGGER */
SELECT * FROM PRODUTO;

UPDATE PRODUTO SET VALOR_UNITARIO=900 WHERE COD_PRODUTO=2;

SELECT * FROM HISTORICO_PRODUTO;

/* TESTE OUTRA TRIGGER  */ 
DELIMITER // 
CREATE TRIGGER EXCLUI_HISTORICO_DE_PRODUTO
AFTER DELETE ON PRODUTO 
  FOR EACH ROW
  BEGIN 
        SET SQL_SAFE_UPDATES = 0;
        DELETE FROM  HISTORICO_PRODUTO WHERE COD_PRODUTO = OLD.COD_PRODUTO;
        SET SQL_SAFE_UPDATES = 1;
  END //     
  
  DROP TRIGGER EXCLUI_HISTORICO_DE_PRODUTO;

/* TESTE TRIGGER */ 
UPDATE PRODUTO SET VALOR_UNITARIO=1750 WHERE COD_PRODUTO=5;

SELECT * FROM PRODUTO;
SELECT * FROM HISTORICO_PRODUTO;

DELETE FROM PRODUTO WHERE COD_PRODUTO = 5;